# Generated by Django 3.0.5 on 2020-05-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='sNo',
            new_name='sno',
        ),
    ]
